services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./dist:/var/www/
      - ./logs/nginx:/var/log/nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
